sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hertzbit/docker-frontend-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hertzbit/docker-frontend-app npm run test -- -- coverage
